const Primer_ape = [
	"Garcia",
	"Hernandez",
	"Lopez",
	"Martinez",
	"Gonzalez",
	"Rodriguez",
	"Perez",
	"Sanchez",
	"Ramirez",
	"Flores",
	"Torres",
	"Rivera",
	"Gomez",
	"Diaz",
	"Reyes",
	"Cruz",
	"Morales",
	"Ortega",
	"Mendoza",
	"Castillo",
	"Chavez",
	"Mendoza",
	"Delgado",
	"Vargas",
	"Silva",
	"Rojas",
	"Guerrero",
	"Estrada",
	"Mejia",
	"Ramos",
	"Ortiz",
	"Molina",
	"Campos",
	"Cortes",
	"Guzman",
	"Pena",
	"Soto",
	"Santos",
	"Navarro",
	"Mora",
	"Herrera",
	"Aguilar",
	"Jimenez",
	"Rios",
	"Lara",
	"Vazquez",
	"Valdez",
	"Vega",
	"Miranda",
	"Escobar",
	"Montes",
	"Luna",
	"Leyva",
	"Barrera",
	"Castaneda",
	"Rubio",
	"Orozco",
	"Arellano",
	"Carrillo",
	"Avila",
	"Salas",
	"Carrasco",
	"Esparza",
	"Ibarra",
	"Benitez",
	"Pacheco",
	"Solis",
	"Palacios",
	"Escobedo",
	"Quintero",
	"Cervantes",
	"Rangel",
	"Calderon",
	"Olvera",
	"Tovar",
	"Peralta",
	"Serrano",
	"Valencia",
	"Uribe",
];

const Segundo_Ape = [
	"Smith",
	"Johnson",
	"Williams",
	"Brown",
	"Jones",
	"Miller",
	"Davis",
	"Garcia",
	"Rodriguez",
	"Wilson",
	"Martinez",
	"Anderson",
	"Taylor",
	"Thomas",
	"Hernandez",
	"Moore",
	"Martin",
	"Jackson",
	"Thompson",
	"White",
	"Lopez",
	"Lee",
	"Gonzalez",
	"Harris",
	"Clark",
	"Lewis",
	"Young",
	"Walker",
	"Hall",
	"Allen",
	"King",
	"Wright",
	"Scott",
	"Green",
	"Baker",
	"Adams",
	"Nelson",
	"Hill",
	"Ramirez",
	"Campbell",
	"Mitchell",
	"Roberts",
	"Carter",
	"Phillips",
	"Evans",
	"Turner",
	"Torres",
	"Parker",
	"Collins",
	"Edwards",
	"Stewart",
	"Flores",
	"Morris",
	"Nguyen",
	"Murphy",
	"Cook",
	"Rogers",
	"Morgan",
	"Peterson",
	"Cooper",
	"Reed",
	"Bailey",
	"Bell",
	"Gomez",
	"Kelly",
	"Howard",
	"Ward",
	"Cox",
	"Diaz",
	"Richardson",
	"Wood",
	"Watson",
	"Brooks",
	"Bennett",
	"Gray",
	"James",
];

const Primer_Nombre = [
	"Sofia",
	"Isabella",
	"Valentina",
	"Emma",
	"Mia",
	"Camila",
	"Ximena",
	"Valeria",
	"Lucia",
	"Ava",
	"Mariana",
	"Maria",
	"Fernanda",
	"Regina",
	"Renata",
	"Alejandra",
	"Paula",
	"Abril",
	"Danna",
	"Jimena",
	"Julieta",
	"Andrea",
	"Ana",
	"Sara",
	"Victoria",
	"Emily",
	"Daniela",
	"Gabriela",
	"Natalia",
	"Montserrat",
	"Catalina",
	"Ximena",
	"Fatima",
	"Paola",
	"Luna",
	"Monserrat",
	"Antonia",
	"Elena",
	"Carolina",
	"Bianca",
	"angela",
	"Rosa",
	"Regina",
	"Mariana",
	"Clara",
	"Maria Jose",
	"Valery",
	"Alexa",
	"Allison",
	"Jennifer",
	"Zoe",
	"Ana Sofia",
	"Gael",
	"Diego",
	"Emiliano",
	"Sebastian",
	"Mateo",
	"Daniel",
	"Santiago",
	"Benjamin",
	"Samuel",
	"Jesús",
	"David",
	"Alejandro",
	"Jose",
	"Eduardo",
	"angel",
	"Miguel",
	"Luis",
	"Carlos",
	"Javier",
	"Fernando",
	"Jorge",
	"Juan",
	"Adrian",
	"Martin",
	"Andres",
	"Leonardo",
	"Joaquin",
	"Hector",
	"oscar",
	"Ricardo",
	"Isaac",
	"Mario",
	"Pedro",
	"Raúl",
	"Cristian",
	"Luis angel",
];

const Segundo_Nombre = [
	"Alejandro",
	"Maria",
	"Fernanda",
	"Jose",
	"Sofia",
	"Guadalupe",
	"Manuel",
	"Isabel",
	"Miguel",
	"Elena",
	"Francisco",
	"Victoria",
	"Luis",
	"Paula",
	"Ricardo",
	"Valentina",
	"Javier",
	"Andrea",
	"Sebastian",
	"Gabriela",
	"Emilio",
	"Camila",
	"Eduardo",
	"Lucia",
	"Carlos",
	"Ana",
	"Daniel",
	"Catalina",
	"Pedro",
	"Fatima",
	"Mauricio",
	"Ximena",
	"Rafael",
	"Valeria",
	"Roberto",
	"Renata",
	"Arturo",
	"Montserrat",
	"Hugo",
	"Abril",
	"Jaime",
	"Jimena",
	"Mario",
	"Julieta",
	"Raúl",
	"Bianca",
	"Salvador",
	"Abril",
	"Alberto",
	"Rosa",
	"Gustavo",
	"Maria Jose",
	"Alejandra",
	"Laura",
	"Gonzalo",
	"Adriana",
	"Felipe",
	"angela",
	"Ignacio",
	"Natalia",
	"Lorenzo",
	"Regina",
	"Raquel",
	"Sara",
	"Vicente",
	"Ximena",
	"Agustin",
	"Clara",
	"alvaro",
	"Carolina",
	"Benjamin",
	"Diana",
	"Diego",
	"Mariana",
	"Ernesto",
	"Paulina",
	"Jorge",
	"Valery",
	"Josue",
	"Ana Sofia",
	"Cesar",
	"Gabriela",
	"Leonardo",
	"Maria Fernanda",
	"Raúl",
	"Maria Jose",
	"Victor",
	"Maria Isabel",
];

var salida = "";
var infoTabla = "";
function generar_alumnos() {
	infoTabla = `DROP DATABASE IF EXISTS sistema_escolar; <br>
CREATE DATABASE IF NOT EXISTS sistema_escolar; <br> 
USE sistema_escolar; <br>  
CREATE TABLE IF NOT EXISTS \`alumnos\` (
\`matricula\` bigint(20) NOT NULL,
\`apellido_1\` varchar(50) DEFAULT NULL,
\`apellido_2\` varchar(50) DEFAULT NULL,
\`nombre\` varchar(50) DEFAULT NULL,
\`correo\` varchar(100) DEFAULT NULL,
\`celular\` varchar(14) DEFAULT NULL,
UNIQUE KEY \`matricula\` (\`matricula\`),
UNIQUE KEY \`correo\` (\`correo\`),
UNIQUE KEY \`celular\` (\`celular\`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci; <br>
INSERT INTO sistema_escolar.alumnos() VALUES<br>`;

	let a = "";
	let num_al = 125000;
	for (let i = 0; i <= num_al; i++) {
		i == num_al ? (a = ";") : (a = ",");
		salida += `
('${("0123456789" + i).slice(-6)}',
'${Primer_ape[Math.floor(Math.random() * 76)]}',
'${Segundo_Ape[Math.floor(Math.random() * 76)]}',
'${Primer_Nombre[Math.floor(Math.random() * 76)]} 
${Segundo_Nombre[Math.floor(Math.random() * 76)]}',
'${("0123456789" + i).slice(-6)}@uthermosillo.edu.mx',
'66${("0123456789" + i).slice(-8)}')${a}<br>`;
	}
	document.getElementById("alumnosP").innerHTML = `${infoTabla}${salida}`;
}

function generarSql() {
	if (salida != "") {
		let contenidoSinBR = `${infoTabla.replaceAll(
			"<br>",
			"\n"
		)}${salida.replaceAll("<br>", "\n")}`;
		let generar = document.createElement("a");
		generar.setAttribute(
			"href",
			"data:text/plain;charset=utf-8," +
				encodeURIComponent(contenidoSinBR)
		);
		generar.setAttribute("download", "alumnos.sql");
		generar.style.display = "none";
		document.body.appendChild(generar);
		generar.click();
		document.body.removeChild(generar);
	}
}
function generarCSV() {
	if (salida != "") {
		let caracteres = "'();`";
		let sinCaracteres = salida.replace(new RegExp("[" + caracteres + "]", "g"), "");
		sinCaracteres = sinCaracteres.replace(/\n/g, "");
		sinCaracteres = sinCaracteres.replaceAll("<br>", "\n");
		let csvContent = "data:text/csv;charset=utf-8," + sinCaracteres;
		let enlace = document.createElement("a");
		enlace.setAttribute("href", encodeURI(csvContent));
		enlace.setAttribute("download", "alumnos.csv");
		enlace.style.display = "none";
		document.body.appendChild(enlace);
		enlace.click();
		document.body.removeChild(enlace);
	}
}
function eliminarCaracteres(texto, caracteres) {
	const expresionRegular = new RegExp(`[${caracteres}]`, "g");
	return texto.replace(expresionRegular, "");
}

function exportar() {
	alert("$mysql -u root -p < alumnos.sql;");
}